name: Test

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['first_branche', 'second_branche']

env:
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_IP: ${{secrets.DB_IP}}
  DB_PORT: ${{secrets.DB_PORT}}
  DB_NAME: ${{secrets.DB_NAME}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  ALGORITHM: ${{secrets.ALGORITHM}}
  ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: began pipeline
        run: echo "pipeline has started"

      - name: pulling code
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: install all dependencies
        run: pip install -r requirements.txt

      - name: test project with pytest
        run: |
          pip install pytest 
          pip install httpx[http2]
          pytest -x -v -s --disable-warnings